"""change column type

Revision ID: 911b20b677e0
Revises: 74bbb42185fa
Create Date: 2024-12-13 23:39:27.069591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911b20b677e0'
down_revision: Union[str, None] = '74bbb42185fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settingss', schema=None) as batch_op:
        batch_op.alter_column('pump_period',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settingss', schema=None) as batch_op:
        batch_op.alter_column('pump_period',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
